export const super_admin_data=(state)=>state.super_admin.status
export const get_super_admin_token=(state)=>state.super_admin.data.token
export const get_super_admin_centers_data=(state)=>state.super_admin.centers
export const get_super_admin_vips_data=(state)=>state.super_admin.vips
export const get_super_admin_status=(state)=>state.super_admin.status
export const get_super_admin_admins_data=(state)=>state.super_admin.admins
export const get_super_admin_message=(state)=>state.super_admin.message
export const get_super_admin_auth=(state)=>state.super_admin.isAuth
export const get_super_admin_teachers=(state)=>state.super_admin.teachers
export const get_super_admin_groups=(state)=>state.super_admin.groups
export const get_super_admin_students=(state)=>state.super_admin.students
